"""Terminal-pain comparison for the Collins rebuttal in the Stocks / Diversification section.

JL Collins's accumulation stance is roughly 100% US stock (VTSAX). On the report's own basis
(1980--2026 block bootstrap, seed 42, dividend re-bin, 1,000 paths, soft / never-sell, taxable
account), this computes the terminal pain -- the 10th-percentile drawdown over the final five years
before retirement -- and the median final wealth for a 100%-US-stock book versus the diversified
30/30/40 mix. It also computes the 2020 COVID fall of the US-stock leg and applies it to the median
all-stock book, for the near-retiree scenario. Writes results/collins_macros.tex.

Run: python3 collins_pain.py
"""
import os, numpy as np
from dca_core import Engine

RESULTS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "results")
N, SEED = 1000, 42


def stats(e, paths, wdict):
    """Terminal pain (10th-pct of the final-5yr drawdown, col 8) and median final wealth, soft."""
    w = e.wvec(wdict)
    M = np.array([e.run_rebin(lambda P, Y: e.run_static(P, Y, w, True), P, Y) for P, Y in paths])
    return np.percentile(M[:, 8], 10) * 100, np.median(M[:, 0]) / 1e6


def main():
    e = Engine("1980", shelter=0.0)                  # taxable -- the report's premise
    paths = e.paths(N, SEED)
    sp, sw = stats(e, paths, {"STOCK": 1.0})                          # 100% US stock (Collins)
    dp, dw = stats(e, paths, {"STOCK": 0.3, "GOLD": 0.3, "BOND": 0.4})  # diversified 30/30/40

    # COVID-2020 fall of the US-stock leg, and what it does to an all-stock book of the median size
    # above -- the concrete near-retiree scenario (peak-to-trough of the stock leg within 2020).
    s = e.adj[e.col["STOCK"]]
    w20 = s.loc["2020-01-01":"2020-12-31"]
    covid = abs(float((w20 / w20.cummax() - 1.0).min()))
    covid_val = sw * (1.0 - covid)

    M = {
        "StockOnlyPain": f"{abs(sp):.0f}",
        "StockOnlyWealth": f"{sw:.2f}",
        "DivPain": f"{abs(dp):.0f}",
        "DivWealth": f"{dw:.2f}",
        "CovidDD": f"{covid * 100:.0f}",
        "StockOnlyCovid": f"{covid_val:.2f}",
    }
    with open(os.path.join(RESULTS, "collins_macros.tex"), "w") as fh:
        fh.write("% Auto-generated by collins_pain.py -- do not edit by hand.\n")
        for k, v in M.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(f"100% US stock:  terminal pain {sp:6.1f}%   median wealth ${sw:.2f}M")
    print(f"30/30/40:       terminal pain {dp:6.1f}%   median wealth ${dw:.2f}M")
    print(f"COVID 2020 stock fall {covid*100:.1f}%:  ${sw:.2f}M -> ${covid_val:.2f}M")
    print("wrote results/collins_macros.tex")


if __name__ == "__main__":
    main()
