"""Emit results/prose_macros.tex -- numbers cited by name in the report body prose.

Mirrors the pattern of scenario_macros.tex / collins_macros.tex etc.: pulls the relevant
values from the MC stores (tpb_1980_*.npy) and emits \\newcommands. The prose then uses
the macros, so every MC rerun auto-updates the body text.

Convention (per the prose style):
  - Magnitudes are stored as POSITIVE numbers; the prose supplies the minus sign for pains.
  - Specific values are 1-decimal; values cited with "roughly"/"approximately" are integer.

Run:  python3 gen_prose_macros.py
"""
import os, numpy as np

RESULTS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "results")
WIN = "1980"


def medW(d, nm):
    return float(np.median(d["data"][nm]["M"][:, 0])) / 1e6


def tpain(d, nm):
    return float(np.percentile(d["data"][nm]["M"][:, 8], 10)) * 100


def fullDD10(d, nm):
    return float(np.percentile(d["data"][nm]["M"][:, 2], 10)) * 100


tx = np.load(os.path.join(RESULTS, f"tpb_{WIN}_taxable.npy"), allow_pickle=True).item()
tf = np.load(os.path.join(RESULTS, f"tpb_{WIN}_taxfree.npy"), allow_pickle=True).item()

# Appendix H (long-window bootstrap, 1962-2026 pool) -- loaded from a separate MC store written by
# longwindow_appendix.py. If the file hasn't been generated yet (fresh clone), skip the macros.
_lw_tx_path = os.path.join(RESULTS, "longwindow_taxable.npy")
_lw_tf_path = os.path.join(RESULTS, "longwindow_taxfree.npy")
if os.path.exists(_lw_tx_path) and os.path.exists(_lw_tf_path):
    _lw_tx = np.load(_lw_tx_path, allow_pickle=True).item()["mc"]
    _lw_tf = np.load(_lw_tf_path, allow_pickle=True).item()["mc"]
    _lw_present = True
else:
    _lw_present = False

# Section 6 -- hard glide (TDF 90>30 hard) vs holding flat (30/30/40 soft), both accounts
hgTxW, hgTxP = medW(tx, "TDF 90>30 hard"), tpain(tx, "TDF 90>30 hard")
hgTfW, hgTfP = medW(tf, "TDF 90>30 hard"), tpain(tf, "TDF 90>30 hard")
ftTxW, ftTxP = medW(tx, "30/30/40 soft"), tpain(tx, "30/30/40 soft")
ftTfW, ftTfP = medW(tf, "30/30/40 soft"), tpain(tf, "30/30/40 soft")

# Hard-glide vs flat full max-DD (10th-percentile, the early-years risk discussion)
hgTxDD = fullDD10(tx, "TDF 90>30 hard")
ftTxDD = fullDD10(tx, "30/30/40 soft")

# 50/25/25 soft pain -- the parenthetical "just outside the cap"
fiveQrtPain = tpain(tx, "50/25/25 soft")

# Permanent Portfolio (hard) pain range across the two accounts -- least to most negative
ppTfPain = tpain(tf, "PermPort hard")          # less negative (tax-free)
ppTxPain = tpain(tx, "PermPort hard")          # more negative (taxable)

# Global median-wealth range across both regimes
all_w = [medW(d, nm) for d in (tx, tf) for nm in d["names"]]
wealthLo, wealthHi = min(all_w), max(all_w)

# Equity-heavy mixes (the "highest-wealth strategies" callout in the intro/key-findings)
heavy_w_names = ["80/20 soft", "80/20 no-reb", "Aggressive soft", "Aggressive no-reb"]
heavy_w_vals = [medW(d, n) for d in (tx, tf) for n in heavy_w_names]
# Drawdown range: include the hard variants and 70/30 no-reb (the broader equity-heavy cluster)
heavy_p_names = heavy_w_names + ["80/20 hard", "Aggressive hard", "70/30 no-reb"]
heavy_p_vals = [tpain(d, n) for d in (tx, tf) for n in heavy_p_names]

# Soft TDF endpoint pain range (taxable) -- "soft glide ends at -33 to -34%"
softTDFPainLo = tpain(tx, "TDF 90>30 soft")
softTDFPainHi = tpain(tx, "TDF 90>3030 soft")

# TDF 90/10->30/70 (hard) pain range across the two accounts -- the headline strategy
tdfHardPainTf = tpain(tf, "TDF 90>30 hard")
tdfHardPainTx = tpain(tx, "TDF 90>30 hard")

# Hard glide tax wealth loss: 1 - taxable/tax-free of the same strategy
taxLossPct = (1 - hgTxW / hgTfW) * 100


def w2(v):    # wealth in $M -- 2 decimals (tenths-of-million = $100k is too coarse for ~$3M comparisons)
    return f"{v:.2f}"


def w1(v):    # wealth in $M -- 1 decimal (for global range claims where $0.1M precision is fine)
    return f"{v:.1f}"


def p1(v):    # percentages (pain, DD) -- 1 decimal
    return f"{v:.1f}"


def i0(v):    # integer (for "roughly" qualifier claims)
    return f"{round(v)}"


lines = [
    "% Auto-generated by gen_prose_macros.py from results/tpb_1980_*.npy.",
    "% Edit gen_prose_macros.py, not this file.",
    f"\\newcommand{{\\HardGlideTxWealth}}{{{w2(hgTxW)}}}",
    f"\\newcommand{{\\HardGlideTxPain}}{{{p1(abs(hgTxP))}}}",
    f"\\newcommand{{\\HardGlideTfWealth}}{{{w2(hgTfW)}}}",
    f"\\newcommand{{\\HardGlideTfPain}}{{{p1(abs(hgTfP))}}}",
    f"\\newcommand{{\\FlatTxWealth}}{{{w2(ftTxW)}}}",
    f"\\newcommand{{\\FlatTxPain}}{{{p1(abs(ftTxP))}}}",
    f"\\newcommand{{\\FlatTfWealth}}{{{w2(ftTfW)}}}",
    f"\\newcommand{{\\FlatTfPain}}{{{p1(abs(ftTfP))}}}",
    f"\\newcommand{{\\HardGlideDD}}{{{p1(abs(hgTxDD))}}}",
    f"\\newcommand{{\\FlatDD}}{{{p1(abs(ftTxDD))}}}",
    f"\\newcommand{{\\FiveTwoFivePain}}{{{p1(abs(fiveQrtPain))}}}",
    f"\\newcommand{{\\PermPortPainLo}}{{{p1(abs(ppTfPain))}}}",
    f"\\newcommand{{\\PermPortPainHi}}{{{p1(abs(ppTxPain))}}}",
    f"\\newcommand{{\\WealthRangeLo}}{{{w1(wealthLo)}}}",
    f"\\newcommand{{\\WealthRangeHi}}{{{w1(wealthHi)}}}",
    f"\\newcommand{{\\EquityHeavyLo}}{{{w1(min(heavy_w_vals))}}}",
    f"\\newcommand{{\\EquityHeavyHi}}{{{w1(max(heavy_w_vals))}}}",
    f"\\newcommand{{\\EquityHeavyPainLo}}{{{p1(abs(max(heavy_p_vals)))}}}",   # least negative (smallest magnitude)
    f"\\newcommand{{\\EquityHeavyPainHi}}{{{p1(abs(min(heavy_p_vals)))}}}",   # most negative (largest magnitude)
    f"\\newcommand{{\\SoftTDFPainLo}}{{{p1(abs(softTDFPainLo))}}}",
    f"\\newcommand{{\\SoftTDFPainHi}}{{{p1(abs(softTDFPainHi))}}}",
    f"\\newcommand{{\\TdfHardPainLo}}{{{p1(abs(tdfHardPainTf))}}}",
    f"\\newcommand{{\\TdfHardPainHi}}{{{p1(abs(tdfHardPainTx))}}}",
    f"\\newcommand{{\\HardGlideTaxLossPct}}{{{i0(taxLossPct)}}}",
]

if _lw_present:
    def _lwmed(mc_dict, nm): return float(np.median(mc_dict[nm][:, 0])) / 1e6
    def _lwtp(mc_dict, nm):  return float(np.percentile(mc_dict[nm][:, 8], 10)) * 100
    lines += [
        f"\\newcommand{{\\LongwindowTdfTxWealth}}{{{w2(_lwmed(_lw_tx, 'TDF 90/10->30/70 hard'))}}}",
        f"\\newcommand{{\\LongwindowTdfTxPain}}{{{p1(abs(_lwtp(_lw_tx, 'TDF 90/10->30/70 hard')))}}}",
        f"\\newcommand{{\\LongwindowTdfTfWealth}}{{{w2(_lwmed(_lw_tf, 'TDF 90/10->30/70 hard'))}}}",
        f"\\newcommand{{\\LongwindowTdfTfPain}}{{{p1(abs(_lwtp(_lw_tf, 'TDF 90/10->30/70 hard')))}}}",
        f"\\newcommand{{\\LongwindowGldTxWealth}}{{{w2(_lwmed(_lw_tx, 'glD hard'))}}}",
        f"\\newcommand{{\\LongwindowGldTxPain}}{{{p1(abs(_lwtp(_lw_tx, 'glD hard')))}}}",
        f"\\newcommand{{\\LongwindowGldTfWealth}}{{{w2(_lwmed(_lw_tf, 'glD hard'))}}}",
        f"\\newcommand{{\\LongwindowGldTfPain}}{{{p1(abs(_lwtp(_lw_tf, 'glD hard')))}}}",
    ]

out = os.path.join(RESULTS, "prose_macros.tex")
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {out} ({len(lines) - 2} macros)")
