"""Regenerate the comprehensive appendix tables (wealth_tables.tex) on the 35-strategy,
method-B-terminal-pain basis. For each window x tax treatment: one longtable. The strategy name is a
multirow merge; the next column names the metric; the remaining four columns give that metric's value
for Actual | MC median-by-return | MC 10th-pct-by-return | MC 10th-pct-by-maxDD. One row per metric:
Wealth / IRR / max DD (full) / final-5yr DD / peak-to-trough yr / recovery / Sharpe / Calmar.
MC reps read from results/tpb_*.npy; the single Actual backtest is recomputed."""
import os, numpy as np
from dca_core import Engine

SRC = [("1980", "taxable"), ("1980", "tax-free")]   # 1980 unified 8-leg basis is the single window
BASE = os.path.dirname(os.path.abspath(__file__)) + "/"

def field_fns(e):
    R = e.field()
    if all(r in e.roles for r in ("STOCK", "BOND")):
        sb = (e.wvec({"STOCK": 0.9, "BOND": 0.1}), e.wvec({"STOCK": 0.3, "BOND": 0.7}))
        t30 = e.wvec({"STOCK": 0.3, "GOLD": 0.3, "BOND": 0.4}) if "GOLD" in e.roles else None
        R = R + [("TDF 90>30 soft", lambda P, Y: e.run_contglide(P, Y, sb[0], sb[1], "soft")),
                 ("TDF 90>30 hard", lambda P, Y: e.run_contglide(P, Y, sb[0], sb[1], "hard"))]
        if t30 is not None:
            R = R + [("TDF 90>3030 soft", lambda P, Y: e.run_contglide(P, Y, sb[0], t30, "soft")),
                     ("TDF 90>3030 hard", lambda P, Y: e.run_contglide(P, Y, sb[0], t30, "hard"))]
    return R

# metric cols: 0 fv, 1 irr, 2 fullDD, 3 sharpe, 4 dur, 5 recov, 6 ptt, 7 resid, 8 termDD
def cal(p): return p[1] / abs(p[2]) if abs(p[2]) > 1e-9 else float("nan")
def rec(p): return f"{p[4]:.1f}y" if p[5] == 1 else f"${p[7]*100:.0f}\\%$\\,end"
def esc(s): return s.replace(">", "$\\to$").replace("%", "\\%").replace("&", "\\&")

# (metric label, formatter) -- one table row each, in display order
METRICS = [
    ("Wealth",         lambda p: f"${p[0]/1e6:.2f}$M"),
    ("IRR",            lambda p: f"{p[1]*100:.1f}\\%"),
    ("Max DD (full)",  lambda p: f"${p[2]*100:.1f}\\%$"),
    ("Final-5yr DD",   lambda p: f"${p[8]*100:.1f}\\%$"),
    ("Peak-to-trough", lambda p: f"{p[6]:.1f}y"),
    ("Recovery",       lambda p: rec(p)),
    ("Sharpe",         lambda p: f"{p[3]:.2f}"),
    ("Calmar",         lambda p: f"{cal(p):.2f}"),
]

out = ["% Auto-generated by gen_tables2.py from results/tpb_*.npy + actual recompute -- do not edit by hand.", ""]
body = []   # (win,treg,nm, fin,irr,sharpe,maxDD, medWealth, termPain, medSharpe) -- figures quoted in the report BODY
hdr = ("Strategy & Metric & Actual & \\makecell{MC median\\\\by return} & \\makecell{MC 10th pct\\\\by return} "
       "& \\makecell{MC 10th pct\\\\by max DD} \\\\")
for win, treg in SRC:
    tag = "taxfree" if treg == "tax-free" else "taxable"
    d = np.load(f"{BASE}results/tpb_{win}_{tag}.npy", allow_pickle=True).item()
    names, data = d["names"], d["data"]
    e = Engine(win, shelter=(1.0 if tag == "taxfree" else 0.0)); Pa, Ya = e.actual()
    fns = dict(field_fns(e))
    out.append(f"\\paragraph{{{win}, {treg}.}} "
               "{\\scriptsize The figure under each strategy name is its \\emph{terminal pain}, the "
               "10th-percentile final-5yr drawdown across all 1{,}000 paths. Each strategy spans eight "
               "rows, one per metric. \\emph{Final-5yr DD} is \\emph{that path's own} terminal drawdown; "
               "\\emph{Recovery} is years to recover, or residual DD at the window end.}")
    title = ("\\toprule \\multicolumn{6}{@{}l}{\\normalsize\\textbf{Appendix G \\textemdash\\ " +
             f"{win}, {treg}" + "}} \\\\ \\midrule " + hdr + " \\midrule")
    out.append("{\\scriptsize\\renewcommand{\\arraystretch}{1.05}")
    out.append("\\begin{longtable}{@{}ll cccc@{}}")
    out.append(title + " \\endfirsthead")
    out.append(title + " \\endhead")
    out.append("\\bottomrule \\endfoot")
    for nm in names:
        M = data[nm]["M"]; n = len(M)
        med = M[np.argsort(M[:, 1])[int(round(0.50 * n))]]
        r10 = M[np.argsort(M[:, 1])[int(round(0.10 * n))]]
        d10 = M[np.argsort(M[:, 2])[int(round(0.10 * n))]]
        act = fns[nm](Pa, Ya)
        reps = [act, med, r10, d10]
        tp = np.percentile(M[:, 8], 10)   # strategy-level terminal pain = 10th-pct of terminal DD across paths
        iw = int(np.argsort(M[:, 0])[n // 2])   # path-coherent median-by-wealth path
        ish = int(np.argsort(M[:, 3])[n // 2])  # path-coherent median-by-Sharpe path
        body.append((win, treg, nm, act[0], act[1], act[3], act[2],
                     float(M[iw, 0]), float(tp), float(M[ish, 3]),   # each "median X" from the median path BY X
                     float(d10[2])))   # 10th-pct-by-maxDD path's full drawdown (the youth crash for a glide)
        namecell = f"\\makecell[l]{{{esc(nm)}\\\\{{\\scriptsize term.\\ pain ${tp*100:.0f}\\%$}}}}"
        for i, (lab, fn) in enumerate(METRICS):
            vals = " & ".join(fn(r) for r in reps)
            head = f"\\multirow{{8}}{{*}}{{{namecell}}}" if i == 0 else ""
            term = " \\\\*" if i < len(METRICS) - 1 else " \\\\ \\hline"
            out.append(f"{head} & {lab} & {vals}{term}")
    out.append("\\end{longtable}}")
    out.append("")

with open(BASE + "wealth_tables.tex", "w") as _fh:
    _fh.write("\n".join(out))
print(f"wrote wealth_tables.tex ({len(out)} lines, {len(SRC)} tables)")

# --- figures quoted in the report BODY (Exec Summary / Key Findings / The Choice / Q&A), so they
#     are sourced reproducibly from the same run rather than transcribed by hand ---
BODYSEL = ["30/30/40 soft", "40/30/30 soft", "40/25/35 soft", "50/25/25 soft", "PermPort soft",
           "60/40 soft", "Conservative soft", "Aggressive soft", "US/Intl 50/50 soft",
           "GEM monthly", "GEM quarterly", "TDF 90>30 hard", "TDF 90>3030 hard", "TDF 90>3030 soft",
           "glD hard", "TrendFollow", "MeanRevert", "TF+MR"]
print("\n=== report-body figures: actual Fin/IRR/Sharpe/MaxDD | MC medWealth / termPain / medSharpe ===")
for win, treg in SRC:
    print(f"-- {win} {treg} --")
    for r in body:
        if r[0] == win and r[1] == treg and r[2] in BODYSEL:
            print(f"  {r[2]:18s} ${r[3]/1e6:4.2f}M {r[4]*100:5.1f}% {r[5]:5.2f} {r[6]*100:6.1f}%"
                  f"  |  ${r[7]/1e6:4.2f}M  {r[8]*100:6.1f}%  {r[9]:.2f}  10thDD {r[10]*100:5.1f}%")
def _row(win, treg, nm):
    rs = [r for r in body if r[0] == win and r[1] == treg and r[2] == nm]
    return rs[0] if rs else None
print(f"\n1980: strategies with MC median > $3M AND terminal pain shallower than -30%, in BOTH accounts:")
names1980 = sorted({r[2] for r in body if r[0] == "1980"})
def _ok(treg, nm):
    r = _row("1980", treg, nm); return r is not None and r[7] > 3e6 and r[8] > -0.30
both = [nm for nm in names1980 if _ok("taxable", nm) and _ok("tax-free", nm)]
print(f"  {len(both)} of {len(names1980)}: {', '.join(both)}")
